import { StyleSheet } from "react-native";
import { colors, fonts } from "../../styles/theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.fundo,
    padding: 16,
  },
  centerContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.fundo,
  },
  title: {
    fontSize: 22,
    fontFamily: fonts.title,
    color: colors.titulo,
    textAlign: "center",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 20,
  },
  card: {
    backgroundColor: colors.fundoPrincipal,
    borderRadius: 16,
    padding: 18,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: colors.bordaSuave,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
  },
  cardTitle: {
    fontSize: 16,
    fontFamily: fonts.bodyBold,
    fontWeight: "700",
    color: colors.roxo,
    marginBottom: 8,
  },
  cardText: {
    fontSize: 14,
    fontFamily: fonts.body,
    color: colors.texto,
    marginBottom: 6,
  },
  bold: {
    fontFamily: fonts.bodyBold,
    fontWeight: "700",
  },
  detailsContainer: {
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderColor: colors.bordaSuave,
  },
  linkText: {
    color: colors.vinhoMedio,
    marginTop: 8,
    fontFamily: fonts.bodyBold,
    textDecorationLine: "underline",
    letterSpacing: 0.5,
  },
  button: {
    backgroundColor: colors.roxo,
    borderRadius: 20,
    paddingVertical: 10,
    paddingHorizontal: 20,
    marginTop: 16,
    alignItems: "center",
  },
  buttonText: {
    color: colors.textoInvertido,
    fontFamily: fonts.bodyBold,
    fontWeight: "bold",
    letterSpacing: 0.5,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  emptyText: {
    fontSize: 16,
    fontFamily: fonts.body,
    color: colors.textoSecundario,
    textAlign: "center",
  },
  flatListEmpty: {
    flexGrow: 1,
  },
  modalBackground: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.3)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContainer: {
    width: "88%",
    backgroundColor: colors.fundoPrincipal,
    borderRadius: 20,
    padding: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 5,
  },
  buttonClose: {
    backgroundColor: colors.vinhoPrincipal,
    marginTop: 24,
  },
});